[package]
name = "timeline_core"
version = "0.1.0"
edition = "2024"
license-file.workspace = true
description = "Core Timeline library for the Timeline GUI Editor based on the Temporal Engine"
repository.workspace = true
keywords = ["timeline", "temporal", "date and time", "event", "history"]
categories = ["date-and-time", "localization"]

[dependencies]
serde = { version = "1.0.228", features = ["serde_derive"] }
slotmap = { version = "1.1.1", features = ["serde"] }
temporal_rs = "0.2.3"

thiserror = "2.0.18"

[dev-dependencies]
serde_json = "1.0.149"

[features]
date_iteration = []
